# Numpy

NumPy stands for numerical python. NumPy is a library written for scientific computing and data analysis. It stands for numerical python and also known as array oriented computing. The most basic object in NumPy is the ndarray, or simply an array which is an n-dimensional, homogeneous array.

# Reasons to Use Numpy

Numpy is:
-Fast
-Convenient

Numpy array is much faster compared to python lists. Numpy is implemented in C-language. It also provide some nice methods for linea algebra manipulations.

# Let's Start Numpy

In [2]:
import numpy as np

In [5]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3x3 matrix
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print(type(a)) # checking the type

<class 'numpy.ndarray'>


In [8]:
a.shape # To check dimensions (rows, columns)

(3, 3)

# Comparing Numpy Array With Python Lists

Numpy array computation time is much smaller than python lists. Let us verify:

In [10]:
c = range(10000)
%timeit [i**3 for i in c] # list

3.19 ms ± 48.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
c_numpy = np.arange(10000)
%timeit c_numpy**3

25.5 µs ± 452 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Numpy is much much faster than python lists.

# Numpy 

In [12]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a = a.reshape(3,3)

In [14]:
a.shape

(3, 3)

In [16]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.eye(3) # Identity Matix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
v = np.array([1,2,3])
np.tile(v,(3,1)) # stack 3 copies of v on top of each other

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [21]:
# between 0 and 1
np.random.random()

0.973884747137836

In [22]:
# 100 values between 1 and 50
a = np.linspace(1,50,100)
a

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

### Vertical and Horizontal Stacking

In [27]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])

In [28]:
print(np.vstack((a,b))) # vertical stacking

[[1 2 3]
 [4 5 6]]


In [29]:
print(np.hstack((a,b))) # horizontal stacking

[[1 2 3 4 5 6]]


### Mathematical Operations

In [30]:
a = np.arange(1,10)

In [31]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [32]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [34]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [35]:
np.std(a)

2.581988897471611

In [48]:
a = np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [49]:
np.sum(a)

10

In [46]:
np.sum(a, axis=0)

array([4, 6])

In [47]:
np.sum(a, axis=1)

array([3, 7])

In [67]:
np.dot(a,a) # Dot Product

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [71]:
np.linalg.det(a) # Determinant

-9.51619735392994e-16

In [75]:
np.linalg.inv(a) # Inverse

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [77]:
a.T # Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### Indexing and Sub-Section Indexing

In [54]:
a = np.arange(1,10).reshape(3,3)

In [60]:
a[:] # Select all elements

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# let us select the 2nd row
a[1:2,:]

array([[4, 5, 6]])

In [64]:
# let us select the 2nd column
a[:,1:2]

array([[2],
       [5],
       [8]])

In [66]:
#let us select the portion 2,3,5,6
a[:2,1:]

array([[2, 3],
       [5, 6]])

In [78]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
a > 2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [80]:
a[a> 2]

array([3, 4, 5, 6, 7, 8, 9])